### ISSUE TITLE
Can Support WASM?

### ISSUE THREAD

**Issue by shenshouer** [niklak/dom_query#5]
Does this crate support WASM ?

**Comment by niklak** [comment]
I am surprised. But it was compiled some tests with `wasm-pack test --node`. 
**Tests are passing.**
So yes it supports WASM, but I suppose this may have some issues. I will try to add some tests for wasm target later.

**Comment by niklak** [comment]
I've adataped the tests to run with wasm-bindgen-test-runner and it runs successful on my PC.
However there was some problems running same tests with github actions CI. 
At first it was all good but after some time i tried to simply re-run wasm ci jobs and it started to fail. 
After that I set up self-hosted runner and then wasm CI was successful.

So my answer is: Yes, It supports WASM. 
But to be completely sure, I need to build some simple wasm app, but currently I do not have much time on this.
